apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-drcq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-drcq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-drcq
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-drcq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-drcq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iatj-tenant/rhtap-demo-app/hacbs-test-project-drcq@sha256:d7a5543f4368ce8d0cf0ac747a560d2a8d2c9518094efa4dced35314add96a45
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
